version: '3.8'

services:
  
  flask-api:
    build:
      context: .
      dockerfile: Dockfile.linux.dockerfile # windows or linux
    ports:
      - "5000:5000"  # 將 Flask API 服務的 5000 端口映射到主機的 5000 端口
    volumes: 
      # - /F/AnacodaProject/Sentrak_RaspPie_GUI/SentrakSQL:/SentrakDocker/SentrakSQL # 絕對路徑
      - ./SentrakSQL:/SentrakDocker/SentrakSQL  # 相對路徑

      # 外部路徑：容器內部路徑
      

    # environment:
    #   - DATABASE=./Sentrak_RaspPie_GUI/SentrakSQL/SentrakSQL.db
