# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\AnacodaProject\Sentrak_RaspPie_GUI\ui\manu_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(400, 360)
        Frame.setMinimumSize(QtCore.QSize(400, 360))
        Frame.setMaximumSize(QtCore.QSize(400, 360))
        Frame.setSizeIncrement(QtCore.QSize(400, 360))
        Frame.setBaseSize(QtCore.QSize(400, 360))
        self.gridLayoutWidget = QtWidgets.QWidget(Frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 401, 361))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.menu_page_layout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.menu_page_layout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.menu_page_layout.setContentsMargins(0, 0, 0, 0)
        self.menu_page_layout.setSpacing(0)
        self.menu_page_layout.setObjectName("menu_page_layout")
        self.set_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.set_button.setMinimumSize(QtCore.QSize(125, 125))
        self.set_button.setMaximumSize(QtCore.QSize(125, 125))
        self.set_button.setSizeIncrement(QtCore.QSize(125, 125))
        self.set_button.setBaseSize(QtCore.QSize(125, 125))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.set_button.setFont(font)
        self.set_button.setObjectName("set_button")
        self.menu_page_layout.addWidget(self.set_button, 0, 0, 1, 1)
        self.record_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.record_button.setMinimumSize(QtCore.QSize(125, 125))
        self.record_button.setMaximumSize(QtCore.QSize(125, 125))
        self.record_button.setSizeIncrement(QtCore.QSize(125, 125))
        self.record_button.setBaseSize(QtCore.QSize(125, 125))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.record_button.setFont(font)
        self.record_button.setObjectName("record_button")
        self.menu_page_layout.addWidget(self.record_button, 1, 0, 1, 1)
        self.calibrate_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.calibrate_button.setMinimumSize(QtCore.QSize(125, 125))
        self.calibrate_button.setMaximumSize(QtCore.QSize(125, 125))
        self.calibrate_button.setSizeIncrement(QtCore.QSize(125, 125))
        self.calibrate_button.setBaseSize(QtCore.QSize(125, 125))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.calibrate_button.setFont(font)
        self.calibrate_button.setObjectName("calibrate_button")
        self.menu_page_layout.addWidget(self.calibrate_button, 0, 1, 1, 1)
        self.identify_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.identify_button.setMinimumSize(QtCore.QSize(125, 125))
        self.identify_button.setMaximumSize(QtCore.QSize(125, 125))
        self.identify_button.setSizeIncrement(QtCore.QSize(125, 125))
        self.identify_button.setBaseSize(QtCore.QSize(125, 125))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.identify_button.setFont(font)
        self.identify_button.setObjectName("identify_button")
        self.menu_page_layout.addWidget(self.identify_button, 1, 1, 1, 1)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.set_button.setText(_translate("Frame", "設定"))
        self.record_button.setText(_translate("Frame", "記錄"))
        self.calibrate_button.setText(_translate("Frame", "校正"))
        self.identify_button.setText(_translate("Frame", "識別"))
